function res = importCMCAnkleMuscMoments(filename, dataLines)
%IMPORTFILE Import data from a text file
%  GIL1110DOFBACKPACKLAFOANKLEMUSCMOMENTS = IMPORTFILE(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  numeric data.
%
%  GIL1110DOFBACKPACKLAFOANKLEMUSCMOMENTS = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  GIL1110DOFbackpacklAFOAnklemuscmoments = importfile("C:\Users\tm262836\Desktop\Mokadim_Simulation\experiment\GIL06\GIL06_free\Gait10dof18musc_backpack_AFO\CMC\ResultsCMC_allMusc_AFO_test\GIL11_10DOF_backpack_lAFO_Ankle_musc_moments.sto", [8, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Apr-2024 18:23:05

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [8, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "VarName2", "VarName3", "VarName4"];
opts.SelectedVariableNames = ["VarName2", "VarName3", "VarName4"];
opts.VariableTypes = ["string", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");

% Import the data
res = readtable(filename, opts);

%% Convert to output type
res = table2array(res);
end