function [Markers]=Marker_set_gait2354(nb_markers_hand)
% Definition of the markers set used in the M2S
%
%   INPUT
%   - nb_markers_hand: number of markers used on each hand
%   OUTPUT
%   - Markers: set of markers (see the Documentation for the structure) 
%________________________________________________________
%
% Licence
% Toolbox distributed under GPL 3.0 Licence
%________________________________________________________
%
% Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
% Georges Dumont
%________________________________________________________
s=cell(0);

% Trunk
s=[s;{'Sternum' 'STRN' {'On';'On';'On'};...
      'R_Acromium' 'RSHO' {'On';'On';'On'};...
      'L_Acromium' 'LSHO' {'On';'On';'On'};...
      'Top_Head' 'Skull_TopOfHead' {'On';'On';'On'};...
      'V_Sacral' 'V.Sacral' {'On';'On';'On'};...
      'L_ASIS' 'LFWT' {'On';'On';'On'};...
      'R_ASIS' 'RFWT' {'On';'On';'On'}}];

Side={'R';'L'};
% Leg
for i=1:2
    Signe=Side{i};
    s=[s;{[Signe '_Thigh_Upper'] [Signe 'Thigh.Upper'] {'On';'On';'On'};...
          [Signe '_Thigh_Front'] [Signe 'Thigh.Front'] {'On';'On';'On'};...
          [Signe '_Thigh_Rear'] [Signe 'Thigh.Rear'] {'On';'On';'On'};...
          % [Signe '_Knee_Lat'] [Signe 'KNE'] {'On';'On';'On'};...
          % [Signe '_Knee_Med'] [Signe 'KNI'] {''On';'On';'On'};...
          [Signe '_Shank_Upper'] [Signe 'Shank.Upper'] {'On';'On';'On'};...
          [Signe '_Shank_Front'] [Signe 'Shank.Front'] {'On';'On';'On'};...
          [Signe '_Shank_Rear'] [Signe 'Shank.Rear'] {'On';'On';'On'};...
          % [Signe '_Ankle_Lat'] [Signe 'ANE'] {'On';'On';'On'};...
          % [Signe '_Ankle_Med'] [Signe 'ANI'] {'On';'On';'On'};...
          [Signe '_Heel'] [Signe 'HEE'] {'On';'On';'On'};...
          [Signe '_Midfoot_Sup'] [Signe 'Midfoot.Sup'] {'On';'On';'On'};...
          [Signe '_Midfoot_Lat'] [Signe 'Midfoot.Lat'] {'On';'On';'On'};...
          [Signe '_Toe_Lat'] [Signe 'TAR'] {'On';'On';'On'};...
          [Signe '_Toe_Med'] [Signe 'TARI'] {'On';'On';'On'};...
          [Signe '_Toe_Tip'] [Signe 'TOE'] {'On';'On';'On'}}];
%         }]; %#ok<AGROW>
end


Markers=struct('name',{s{:,1}}','anat_position',{s{:,2}}','calib_dir',{s{:,3}}'); %#ok<CCAT1>

end
function [s]=Hand_markers_1(s,Signe)   %#ok<DEFNU>
% 1 marker on the hand
    s=[s;{[Signe 'CAR'] [Signe 'CAR1'] {'Off';'Off';'Off'}}];   
end
function [s]=Hand_markers_2(s,Signe)   %#ok<DEFNU>  
% 2 markers on the hand
    s=[s;{[Signe 'CAR'] [Signe 'CAR2'] {'Off';'Off';'Off'};[Signe 'OHAND'] [Signe 'OHAND'] {'Off';'Off';'Off'}}];    
end    
function [s]=Hand_markers_3(s,Signe)   %#ok<DEFNU>  
% 3 markers on the hand
    s=[s;{[Signe 'CAR'] [Signe 'CAR3'] {'Off';'Off';'Off'};[Signe 'IDX3'] [Signe 'IDX3'] {'Off';'Off';'Off'};[Signe 'PNK3'] [Signe 'PNK3'] {'Off';'Off';'Off'}}];    
end